create table tokens_refresh (
  id bigint generated by default as identity primary key,
  usuario_id bigint references usuarios(id) on delete cascade,
  representante_id bigint references representantes(id) on delete cascade,
  token_hash varchar(64) not null unique,
  familia varchar(36) not null,
  criado_em timestamp with time zone not null,
  expira_em timestamp with time zone not null,
  revogado_em timestamp with time zone,
  constraint ck_tokens_refresh_titular check ((usuario_id is null) <> (representante_id is null))
);

create index idx_tokens_refresh_usuario on tokens_refresh(usuario_id, familia);
create index idx_tokens_refresh_representante on tokens_refresh(representante_id, familia);
