delete from respostas_cotacao;

create table representantes (
  id bigint generated by default as identity primary key,
  nome varchar(120) not null,
  telefone varchar(11) not null unique,
  email varchar(180) not null unique,
  senha_hash varchar(100) not null,
  ativo boolean not null default true,
  versao_autenticacao integer not null default 1,
  ultimo_login_em timestamp with time zone,
  criado_em timestamp with time zone not null,
  atualizado_em timestamp with time zone not null
);

create table tokens_redefinicao_senha_representante (
  id bigint generated by default as identity primary key,
  representante_id bigint not null references representantes(id) on delete cascade,
  token_hash varchar(64) not null unique,
  expira_em timestamp with time zone not null,
  utilizado_em timestamp with time zone,
  criado_em timestamp with time zone not null
);

alter table respostas_cotacao add column representante_id bigint not null references representantes(id);
alter table respostas_cotacao add column chave_distribuidora varchar(220) not null;
alter table respostas_cotacao add column atualizado_em timestamp with time zone not null;
alter table respostas_cotacao add constraint uk_resposta_representante_distribuidora
  unique (cotacao_id, representante_id, chave_distribuidora);

create index idx_representantes_email on representantes(email);
create index idx_tokens_redefinicao_representante on tokens_redefinicao_senha_representante(representante_id);
create index idx_respostas_representante on respostas_cotacao(representante_id);
