alter table produtos rename column gtin to ean;
alter table produtos alter column ean drop not null;
alter table produtos rename constraint uk_produto_empresa_gtin to uk_produto_empresa_ean;
alter table produtos add column identificador_catalogo varchar(260);
update produtos set identificador_catalogo = 'ean:' || ean;
alter table produtos alter column identificador_catalogo set not null;
alter table produtos add constraint uk_produto_empresa_identificador unique (empresa_id, identificador_catalogo);

create table escolhas_compra_cotacao (
  id bigint generated by default as identity primary key,
  item_cotacao_id bigint not null unique references itens_cotacao(id) on delete cascade,
  item_resposta_cotacao_id bigint not null references itens_resposta_cotacao(id) on delete cascade,
  escolhido_por bigint not null references usuarios(id),
  criado_em timestamp with time zone not null,
  atualizado_em timestamp with time zone not null
);

create index idx_escolhas_compra_resposta on escolhas_compra_cotacao(item_resposta_cotacao_id);
