alter table empresas add column cnpj varchar(14);
alter table empresas add constraint uk_empresas_cnpj unique (cnpj);

alter table escolhas_compra_cotacao alter column item_resposta_cotacao_id drop not null;
alter table escolhas_compra_cotacao add column campeao_manual boolean not null default true;
alter table escolhas_compra_cotacao add column quantidade_desejada integer;
alter table escolhas_compra_cotacao add column quantidade_campeao integer;
alter table escolhas_compra_cotacao add column justificativa_estoque varchar(500);

create table pedidos_compra (
  id bigint generated by default as identity primary key,
  cotacao_id bigint not null references cotacoes(id) on delete cascade,
  resposta_cotacao_id bigint not null references respostas_cotacao(id),
  numero varchar(40) not null unique,
  status varchar(30) not null,
  nome_farmacia varchar(160) not null,
  cnpj_farmacia varchar(14) not null,
  nome_distribuidora varchar(160) not null,
  cnpj_distribuidora varchar(14),
  nome_representante varchar(120) not null,
  telefone_representante varchar(30) not null,
  email_representante varchar(180),
  observacao varchar(500),
  total numeric(15,4) not null,
  criado_por bigint not null references usuarios(id),
  gerado_em timestamp with time zone not null,
  compartilhado_em timestamp with time zone,
  atualizado_em timestamp with time zone not null,
  constraint uk_pedido_cotacao_resposta unique (cotacao_id, resposta_cotacao_id)
);

create table itens_pedido_compra (
  id bigint generated by default as identity primary key,
  pedido_compra_id bigint not null references pedidos_compra(id) on delete cascade,
  item_cotacao_id bigint not null references itens_cotacao(id),
  ean varchar(14),
  produto varchar(240) not null,
  quantidade integer not null check (quantidade > 0),
  preco_unitario numeric(15,4) not null,
  subtotal numeric(15,4) not null,
  justificativa_estoque varchar(500)
);

create index idx_pedidos_compra_cotacao on pedidos_compra(cotacao_id);
create index idx_itens_pedido_compra_pedido on itens_pedido_compra(pedido_compra_id);
