alter table usuarios add column versao_autenticacao integer not null default 1;

create table tokens_redefinicao_senha_usuario (
  id bigint generated by default as identity primary key,
  usuario_id bigint not null references usuarios(id) on delete cascade,
  token_hash varchar(64) not null unique,
  expira_em timestamp with time zone not null,
  utilizado_em timestamp with time zone,
  criado_em timestamp with time zone not null
);

create index idx_tokens_redefinicao_usuario on tokens_redefinicao_senha_usuario(usuario_id);
