create table versoes_plano_compra (
  id bigint generated by default as identity primary key,
  cotacao_id bigint not null references cotacoes(id) on delete cascade,
  numero integer not null,
  acao varchar(40) not null,
  descricao varchar(240) not null,
  criado_por bigint not null references usuarios(id),
  restaurada_de_id bigint references versoes_plano_compra(id),
  total_plano numeric(15,4) not null,
  criado_em timestamp with time zone not null,
  constraint uk_versao_plano_cotacao_numero unique (cotacao_id, numero)
);

create table itens_versao_plano_compra (
  id bigint generated by default as identity primary key,
  versao_id bigint not null references versoes_plano_compra(id) on delete cascade,
  item_cotacao_id bigint not null references itens_cotacao(id),
  escolha_presente boolean not null,
  item_resposta_cotacao_id bigint references itens_resposta_cotacao(id),
  campeao_manual boolean not null,
  quantidade_desejada integer,
  quantidade_campeao integer,
  justificativa_estoque varchar(500),
  constraint uk_item_versao_plano unique (versao_id, item_cotacao_id)
);

create table respostas_versao_plano_compra (
  id bigint generated by default as identity primary key,
  versao_id bigint not null references versoes_plano_compra(id) on delete cascade,
  resposta_cotacao_id bigint not null references respostas_cotacao(id),
  incluida boolean not null,
  constraint uk_resposta_versao_plano unique (versao_id, resposta_cotacao_id)
);

create index idx_versoes_plano_cotacao on versoes_plano_compra(cotacao_id, numero desc);
create index idx_itens_versao_plano on itens_versao_plano_compra(versao_id);
create index idx_respostas_versao_plano on respostas_versao_plano_compra(versao_id);
